### ISSUE TITLE
Feature: More contribution types

### ISSUE THREAD

**Issue by dpkristensen** [dpk5081/eso-guild-contributions#5]
Would be nice to allow more contribution types (activities, etc...)
Challenges/questions:
* What types?
* How many to complete?  Does each have a mandatory/optional requirement?

**Comment by slippycheeze** [comment]
Our guild offers two things that are not presently available for contributions:

1. Contributions in materials by mail, based on market price.  I suspect that is on the difficult side, since it would want MM, TTC, and/or Nern AH integration to get the pricing data.

2. Contributions in the unit of 1,000 gold, unlimited amount, no minimum, with each 1k giving one "raffle" ticket in return.    I'll file a separate feature request for that one, and describe roughly the UI I imagine for it, and the interactions, in an effort to communicate my desires.

**Comment by dpkristensen** [comment]
Closing issue for discontinued development.
